### ISSUE TITLE
function documentation is separated from the functions

### ISSUE THREAD

**Issue by EnricoGiampieri** [JustWhit3/higgs-decay-classification#1]
it is a general good practice in python for the documentation about the function to be part of the function definition.

**Comment by JustWhit3** [comment]
Last issue for the resolution of the problem: https://github.com/JustWhit3/Software_and_Computing_program/commit/2cb96489a604faa8d78ad5e5e9da34774e2aee37.

I did also this 2 things (not specified in the issues):
1) Added the documentation links in the main README file.
2) Moved all the defined functions from the main program to some proper headers and than, I've included them in the program itself as modules.
